import { useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Bot, ChevronDown, Maximize2, Mic, Send, Sparkles, X } from 'lucide-react';
import type { ScreenId } from '../data/nav';

type Msg = { role: 'user' | 'assistant'; text: string; confidence?: number; sources?: string[] };

const prompts = [
  'What needs Charl’s attention today?',
  'Why did DSO increase to 35 days?',
  'Which stores represent the biggest banking risk?',
  'Which transformation project should be accelerated?',
];

function answerFor(query: string, active: ScreenId): Msg {
  const q = query.toLowerCase();
  const source = ['TiAuto June 2026 MBR', 'Finance Intelligence demonstration model'];
  if (q.includes('dso') || q.includes('collection') || q.includes('fleet') || q.includes('receivable')) return { role:'assistant', confidence:95, sources:source, text:'DSO increased from 33 to 35 days in June, while the three-month average is 34 days and the SLA range remains 36–40 days. The issue is not SLA failure; it is directional deterioration. Focus on Top 30 Fleet balances, 60+ day ageing, and identified versus unidentified allocations. Launch a two-week Fleet collections sprint measured on cash recovered and ageing reduced.' };
  if (q.includes('store') || q.includes('bank') || q.includes('cash') || q.includes('deposit')) return { role:'assistant', confidence:96, sources:source, text:'June recorded R5.3m in cash and card drops not banked across 468 transactions. Cash deposits were R6.2m over 2,068 transactions and card deposits R117m over 3,031 transactions. Polokwane, Umhlanga and Alberton rank highest by cash value. Age every exception by store, value and days outstanding, then escalate repeat offenders rather than waiting for month-end.' };
  if (q.includes('transformation') || q.includes('project') || q.includes('python') || q.includes('automation')) return { role:'assistant', confidence:93, sources:source, text:'Accelerate Project 32 first: BIO payment posting and SAGE upload automation. Phase 1 is complete and the identified opportunity is approximately 32 hours, but value is blocked by Python conversion and SI report installation. Recurring journals should follow, with a 31 August target. Assign owners and dates before reporting benefits as committed.' };
  if (q.includes('payment') || q.includes('ap') || q.includes('bio') || q.includes('supplier')) return { role:'assistant', confidence:94, sources:source, text:'BIO approvals totalled R401m in June: R197m Creditors, R5m Stores, R180m Transfers and R19m Head Office. AP captured 246 payments and maintained 100% critical SLA performance. Current operational risks are late store invoices, missing new-store account letters, unreconciled entries and overdue invoices—not payment throughput itself.' };
  if (q.includes('payjustnow')) return { role:'assistant', confidence:92, sources:source, text:'PayJustNow receipts were R5.72m across 814 transactions in June versus R5.73m across 866 transactions in May. Value was effectively flat while transaction count reduced by 52, implying a slightly higher average receipt. The next intelligence step is to monitor settlement timing, exceptions, fees and recurring-journal automation.' };
  if (q.includes('today') || q.includes('attention') || q.includes('focus') || q.includes('risk')) return { role:'assistant', confidence:97, sources:source, text:'Charl’s immediate priorities are: 1) contain DSO movement through Top 30 Fleet and 60+ day action; 2) clear and age the R5.3m not-banked population; 3) resolve R87k in TNM and TWT unallocated receipts; 4) remove store-invoice and new-account-letter bottlenecks; and 5) unblock Python conversion and SI report access for payment automation.' };
  const pageText: Partial<Record<ScreenId,string>> = {
    'command-centre':'You are viewing the June CFO Command Centre. Ask about DSO, BIO approvals, cash/card deposits, executive priorities or transformation decisions.',
    'working-capital':'You are viewing Working Capital. Ask about Fleet collections, 60+ day ageing, DSO or allocation efficiency.',
    reconciliation:'You are viewing Reconciliation Intelligence. June coverage is 100%; ask about consolidated Sumitomo/Dunlop work in progress or exception automation.',
    'mission-control':'You are viewing Agent Mission Control. Ask which TiAuto agents should be activated first and what each one monitors.',
    cashbooks:'You are viewing Cashbooks & Store Banking. Ask about the R5.3m not-banked exposure, top stores, fees, journals or bank accounts.',
    capital:'You are viewing the Transformation Portfolio. Ask about Python conversion, recurring journals, intercompany sheets or ABSA statement downloads.',
  };
  return { role:'assistant', confidence:88, sources:source, text:pageText[active] ?? 'I can analyse TiAuto’s June DSO, Fleet ageing, BIO approvals, PayJustNow receipts, store banking, AP controls, Cashbooks, SLAs and transformation portfolio.' };
}

export default function FinanceIntelligenceChat({ active, onOpenFull }: { active: ScreenId; onOpenFull: () => void }) {
  const [open,setOpen]=useState(false); const [minimised,setMinimised]=useState(false); const [query,setQuery]=useState('');
  const [messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Good day, Charl. June closed on time with strong controls. I am monitoring DSO, Fleet ageing, store banking, AP, Cashbooks and transformation. What would you like to understand?',confidence:97,sources:['TiAuto June 2026 MBR']}]);
  const bottomRef=useRef<HTMLDivElement>(null); const contextLabel=useMemo(()=>active.replaceAll('-',' '),[active]);
  const submit=(text:string)=>{const clean=text.trim();if(!clean)return;setMessages(m=>[...m,{role:'user',text:clean},answerFor(clean,active)]);setQuery('');setTimeout(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),30)};
  return <>{!open&&<motion.button initial={{scale:.85,opacity:0}} animate={{scale:1,opacity:1}} onClick={()=>setOpen(true)} className="fixed right-5 bottom-5 z-50 flex items-center gap-3 rounded-full border border-cyan-300/30 bg-slate-950/90 px-4 py-3 text-white shadow-[0_0_35px_-8px_rgba(34,211,238,.75)] backdrop-blur-xl"><span className="relative flex h-9 w-9 items-center justify-center rounded-full bg-cyan-400/15 text-cyan-300"><Sparkles size={18}/><span className="absolute -right-.5 -top-.5 h-2.5 w-2.5 rounded-full bg-emerald-400 ring-2 ring-slate-950"/></span><span className="text-left"><span className="block text-sm font-semibold">Finance Intelligence</span><span className="block text-[10px] text-cyan-200/70">Ask Charl AI · June MBR</span></span></motion.button>}
  <AnimatePresence>{open&&<motion.section initial={{opacity:0,y:24,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16,scale:.97}} className={`fixed right-4 bottom-4 z-50 w-[min(430px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-cyan-300/20 bg-slate-950/95 text-white shadow-2xl backdrop-blur-2xl ${minimised?'h-auto':'h-[min(680px,calc(100vh-2rem))]'}`}>
    <header className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-400/15 text-cyan-300"><Bot size={18}/></div><div><div className="text-sm font-semibold">Finance Intelligence</div><div className="text-[10px] capitalize text-cyan-200/60">Context: {contextLabel}</div></div></div><div className="flex items-center gap-1"><button onClick={onOpenFull} className="rounded-lg p-2 text-white/60 hover:bg-white/10"><Maximize2 size={15}/></button><button onClick={()=>setMinimised(v=>!v)} className="rounded-lg p-2 text-white/60 hover:bg-white/10"><ChevronDown size={16} className={minimised?'rotate-180':''}/></button><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-white/60 hover:bg-white/10"><X size={16}/></button></div></header>
    {!minimised&&<><div className="h-[calc(100%-142px)] overflow-y-auto px-4 py-4"><div className="mb-4 flex flex-wrap gap-2">{prompts.map(p=><button key={p} onClick={()=>submit(p)} className="rounded-full border border-cyan-300/15 bg-cyan-400/5 px-3 py-1.5 text-[10px] text-cyan-100/80 hover:bg-cyan-400/10">{p}</button>)}</div><div className="space-y-4">{messages.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[90%] rounded-2xl px-4 py-3 text-[12.5px] leading-relaxed ${m.role==='user'?'bg-cyan-400 text-slate-950':'border border-white/10 bg-white/[.055] text-slate-100'}`}>{m.text}{m.role==='assistant'&&m.confidence&&<div className="mt-3 flex items-center justify-between gap-2 border-t border-white/10 pt-2 text-[9px] text-white/45"><span>Confidence {m.confidence}%</span><span>{m.sources?.join(' · ')}</span></div>}</div></div>)}<div ref={bottomRef}/></div></div><div className="absolute bottom-0 left-0 right-0 border-t border-white/10 bg-slate-950/90 p-3"><div className="flex items-end gap-2 rounded-xl border border-white/10 bg-white/[.04] p-2"><button className="rounded-lg p-2 text-white/45"><Mic size={16}/></button><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit(query)}}} rows={1} placeholder="Ask about DSO, stores, BIO, projects..." className="max-h-24 min-h-9 flex-1 resize-none bg-transparent px-1 py-2 text-sm text-white outline-none placeholder:text-white/30"/><button onClick={()=>submit(query)} className="rounded-lg bg-cyan-400 p-2.5 text-slate-950"><Send size={15}/></button></div></div></>}
  </motion.section>}</AnimatePresence></>;
}
